name: random_anime_quotes
description: A Random Anime Quotes I made for fun.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2
  fluttertoast: ^8.0.8
  freezed_annotation: ^1.1.0
  google_fonts: ^2.2.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  hooks_riverpod: ^1.0.3
  json_annotation: ^4.4.0
  path_provider: ^2.0.8
  screenshot: ^1.2.3
  share_plus: ^3.0.4
  shimmer: ^2.0.0
  translator: ^0.1.7

dev_dependencies:
  flutter_native_splash: ^1.3.2
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.3

flutter:
  assets:
    - assets/images/
    - assets/images/theme/

  uses-material-design: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/light.png

  color_dark: "#000000"
  image_dark: assets/dark.png
